### PR TITLE
Redeem ANJ tokens

### PR DESCRIPTION
**Pull request by vidimitrov**
The PR makes some changes on the landing page and introduces the new flow for redeeming an ANJ token to ANTv2.

The UI and the copywriting is implemented. ~The only thing that is left is the real ANJ token integration and testing it end-to-end on a testnet like Rinkeby.~ ✅ 

Here are some screenshots of the current state:

Screenshot 2021-01-25 at 22 48 30

Screenshot 2021-01-25 at 22 48 41

Screenshot 2021-01-31 at 22 17 52

Screenshot 2021-01-25 at 22 49 08

Screenshot 2021-01-25 at 22 49 18

Screenshot 2021-01-27 at 15 30 08

Screenshot 2021-01-27 at 15 30 17

### CODE REVIEW

**Review by nivida — APPROVED** [review]
LGTM! Thanks! I will add the addresses of the mainnet contracts as soon as we have deployed them and after merge this PR.

**Comment by izqui** [comment]
Has the copy been reviewed? IMO this is not ready to go

**Comment by vidimitrov** [comment]
> Has the copy been reviewed? IMO this is not ready to go

Adri and Luis confirmed that the copy is good to go. Let me know if further changes are required :)

**Comment by izqui** [comment]
For starters Aragon Court is there and it should be Aragon Protocol. I also believe that we shouldn't keep referring to ANT as ANTv2 in this context.

**Pull request merged**
